name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Yarn Environment
        run: corepack enable

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        working-directory: .
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test